server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5439/agile_task_service}
    username: ${DATABASE_USERNAME:agile_user}
    password: ${DATABASE_PASSWORD:agile_password}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: ${APP_FLYWAY_ENABLED:false}
    locations: classpath:db/migration

app:
  cache:
    provider: ${APP_CACHE_PROVIDER:NONE}
  storage:
    provider: ${APP_STORAGE_PROVIDER:LOCAL}
    max-file-size: ${APP_STORAGE_MAX_FILE_SIZE:10MB}
    local:
      root-path: ${APP_STORAGE_LOCAL_ROOT_PATH:./data/uploads}
      public-base-url: ${APP_STORAGE_LOCAL_PUBLIC_BASE_URL:http://localhost:8080/resources}
